#!/usr/bin/env bash

function _git_grep_files() {
    if [ $# -gt 0 ]; then
        local path_to_toplevel=$(git rev-parse --show-toplevel)
        if [ $? -eq 0 ]; then
            cd "$path_to_toplevel"
            local cmd="git grep -i -e \"$1\""
            shift
            for var in "$@"
            do
                cmd+=" --and -e $var"
            done
            eval "$cmd"
        fi
    fi
}

_git_grep_files $@
